---
config:
  layout: elk
  theme: base
---

erDiagram

    %% diagram version: 1.0.0

    %% sources:
    %% - dc-radd-transaction-entity.yaml
    %%   id: urn:send:radd-alt:dc-radd-transaction-entity
    %%   version: 0.0.1
    %% - dc-radd-registry.yaml
    %%   id: urn:send:radd-alt:dc-radd-registry
    %%   version: 0.0.1
    %% - dc-operations-iuns-entity.yaml
    %%   id: urn:send:radd-alt:dc-operations-iuns-entity
    %%   version: 0.0.1

    direction LR

    RaddRegistryV2 {
        STRING partnerId PK "NOT NULL"
        STRING locationId PK "NOT NULL"
        OBJECT address
        BOOLEAN appointmentRequired
        STRING creationTimestamp "NOT NULL"
        STRING description
        STRING email
        STRING endValidity
        ARRAY[STRING] externalCodes
        BOOLEAN modifiedAddress "NOT NULL"
        OBJECT normalizedAddress
        STRING openingTime
        STRING partnerType "NOT NULL"
        ARRAY[STRING] phoneNumbers
        STRING startValidity "NOT NULL"
        STRING uid "NOT NULL"
        STRING updateTimestamp "NOT NULL"
        STRING website
        LONG ApproximateCreationDateTime "NOT NULL"
    }

    address {
        STRING addressRow "NOT NULL"
        STRING cap "NOT NULL"
        STRING city "NOT NULL"
        STRING country
        STRING province "NOT NULL"
    }

    normalizedAddress {
        STRING addressRow "NOT NULL"
        OBJECT biasPoint "NOT NULL"
        STRING cap "NOT NULL"
        STRING country
        STRING province "NOT NULL"
        STRING city "NOT NULL"
        STRING latitude "NOT NULL"
        STRING longitude "NOT NULL"
    }

    RaddTransactionEntity {
        STRING transactionId PK "NOT NULL"
        STRING operationType PK "NOT NULL"
        STRING operationId "NOT NULL"
        STRING iun "NOT NULL"
        STRING qrCode
        STRING fileKey
        STRING checksum
        STRING operation_status "NOT NULL"
        STRING recipientId "NOT NULL"
        STRING recipientType "NOT NULL"
        STRING delegateId
        STRING uid "NOT NULL"
        STRING operationStartDate
        STRING operationEndDate
        STRING versionToken
        STRING errorReason
        STRING zipAttachments
        LONG ApproximateCreationDateTime "NOT NULL"
    }

    OperationsIunEntity {
        STRING transactionId PK "NOT NULL"
        STRING iun PK "NOT NULL"
        LONG ApproximateCreationDateTime "NOT NULL"
    }

    %% RELAZIONI

    RaddRegistryV2 ||--|| address : ""
    RaddRegistryV2 ||--|| normalizedAddress : ""
    %% RaddRegistryV2.partnerId = RaddTransactionEntity.partnerId AND RaddRegistryV2.locationId = RaddTransactionEntity.locationId
    RaddRegistryV2 ||--|{ RaddTransactionEntity : "1:N"
    %% RaddTransactionEntity.transactionId = OperationsIunEntity.transactionId
    RaddTransactionEntity ||--|{ OperationsIunEntity : "1:N"


    %% STILE

    style RaddTransactionEntity fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style RaddRegistryV2 fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style address fill:#FFFFFF,stroke:#000000,stroke-width:1px,color:#000000
    style normalizedAddress fill:#FFFFFF,stroke:#000000,stroke-width:1px,color:#000000
    style OperationsIunEntity fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
