---
config:
  layout: elk
  theme: base
---
erDiagram

    %% diagram version: 1.0.1

    %% sources:
    %% - dc-pn-user-attributes.yaml
    %%   id: urn:send:recapiti-deleghe:user-attributes
    %%   version: 1.0.1

    direction LR

    VerificationCode {
        STRING VC-recipient_type-recipient_id PK "NOT NULL"
        STRING addressHash-channelType PK "NOT NULL"
        STRING validationCode "NOT NULL"
        LONG ttl "NOT NULL"
        STRING address
        TIMESTAMP created "NOT NULL"
        TIMESTAMP lastModified "NOT NULL"
    }

    VerifiedAddress {
        STRING VA-recipient_type-recipient_id PK "NOT NULL"
        STRING addressHash-channelType PK "NOT NULL"
        TIMESTAMP created "NOT NULL"
        TIMESTAMP lastModified "NOT NULL"
    }

    DigitalDomicile {
        STRING AB-recipient_type-recipient_id PK "NOT NULL"
        STRING LEGAL-sender_id-type PK "NOT NULL"
        STRING addressHash "NOT NULL"
        TIMESTAMP created "NOT NULL"
        TIMESTAMP lastModified "NOT NULL"
    }

    DigitalAddress {
        STRING AB-recipient_type-recipient_id PK "NOT NULL"
        STRING COURTESY-sender_id-type PK "NOT NULL"
        STRING addressHash "NOT NULL"
        TIMESTAMP created "NOT NULL"
        TIMESTAMP lastModified "NOT NULL"
    }

    Consent {
        STRING CO-recipient_type-recipient_id PK "NOT NULL"
        STRING consent_type-version PK "NOT NULL"
        BOOLEAN accepted "NOT NULL"
        TIMESTAMP created "NOT NULL"
        TIMESTAMP lastModified "NOT NULL"
        STRING channel
    }

    %% RELAZIONI

    %% VerificationCode.addressHash-channelType = VerifiedAddress.addressHash-channelType
    %% Un indirizzo verificato deriva da un precedente record di validazione OTP
    VerificationCode ||--o| VerifiedAddress : "1:0..1"

    %% VerifiedAddress.addressHash-channelType = DigitalDomicile.addressHash
    %% Un indirizzo verificato può essere utilizzato da uno o più domicili legali (default o per ente)
    VerifiedAddress ||--o{ DigitalDomicile : "1:N"

    %% VerifiedAddress.addressHash-channelType = DigitalAddress.addressHash
    %% Un indirizzo verificato può essere utilizzato da uno o più recapiti di cortesia (default o per ente)
    VerifiedAddress ||--o{ DigitalAddress : "1:N"

    %% Consent.recipient_id  = DigitalDomicile.recipient_id 
    %% Alcuni domicili legali (es. SERCQ) richiedono il previo consenso dell'utente
    Consent ||--o{ DigitalDomicile : "1:N"

    %% STILE

    style VerificationCode fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style VerifiedAddress fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style DigitalDomicile fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style DigitalAddress fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style Consent fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000