---
config:
  layout: elk
  theme: base
---
erDiagram

    %% diagram version: 1.0.0

    %% sources:
    %% - dc-pn-mandate.yaml
    %%   id: urn:send:recapiti-deleghe:mandate
    %%   version: 0.0.2

    direction LR

    Deleghe {
        STRING Deleghe_pk PK "NOT NULL"
        STRING sk PK "NOT NULL"
        BOOLEAN b_delegateisperson "NULL"
        BOOLEAN b_delegatorisperson "NULL"
        TIMESTAMP d_validfrom "NULL"
        TIMESTAMP d_validto "NULL"
        NUMBER i_state "NULL"
        STRING s_mandateid "NULL"
        TIMESTAMP t_accepted "NULL"
        TIMESTAMP t_created "NULL"
        ARRAY a_visibilityids "NULL"
        ARRAY a_groups "NULL"
        STRING s_workflowtype "NULL"
        STRING s_srcchannel "NULL"
        ARRAY a_iuns "NULL"
        ARRAY a_taxonomycodes "NULL"
        LONG ApproximateCreationDateTime "NOT NULL"
        }
    a_visibilityids {
        STRING organizationId
    }
    a_groups {
        STRING groupId
    }
    a_iuns {
        STRING iun
    }
    a_taxonomycodes {
        STRING taxonomyCode
    }
    DelegheTriggerHelper {
        STRING DelegheTriggerHelper_pk PK "NOT NULL"
        STRING sk PK "NOT NULL"
        NUMBER i_ttl "NOT NULL"
        STRING s_delegatoruid "NOT NULL"
        STRING s_delegatortype "NOT NULL"
    }

    %% RELAZIONI
    Deleghe ||--o{ a_visibilityids : ""
    Deleghe ||--o{ a_groups : ""
    Deleghe ||--o{ a_iuns : ""
    Deleghe ||--o{ a_taxonomycodes : ""
    Deleghe ||--o| DelegheTriggerHelper : "1:1"

    %% STILE
    style Deleghe fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style a_visibilityids fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style a_groups fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style a_iuns fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style a_taxonomycodes fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style DelegheTriggerHelper fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000