---
config:
  layout: elk
  theme: base
  themeVariables:
    background: "#FFFFFF"
    labelBackgroundColor: "#FFFFFF"
    entityBkgColor: "#FFFFFF"
    attributeBkgColor: "#FFFFFF"
    primaryColor: "#FFFFFF"
---

erDiagram

    %% version: v0.0.1
    %% sources:
    %% - dc-pn-dc-pn-Notifications.yaml v0.0.1
    %% - dc-pn-timeline.yaml v0.0.1

    Direction LR


    NOTIFICATIONS {
        string iun PK
    }

    TIMELINE {
        string timelineElementId PK
        string iun FK
    }

    NOTIFICATIONS_REQUEST {
        string iun PK
    }

    %% RELAZIONI
    NOTIFICATIONS ||--o{TIMELINE : "1:N"
    NOTIFICATIONS_REQUEST ||--|| NOTIFICATIONS : "1:1"
