---
config:
  layout: elk
  theme: base
---

erDiagram

    %% diagram version: <VERSION>

    %% sources:
    %% - dc-radd-transaction-entity.yaml
    %%   id: urn:send:radd-alt:dc-radd-transaction-entity
    %%   version: 0.0.1

    %% CONVENZIONI
    %% - Entità principali in grassetto (**Entity**)
    %% - PK marcata con PK
    %% - Campi obbligatori marcati con "NOT NULL"
    %% - Array e Object di primo livello modellati come entità separate
    %% - Cardinalità esplicitate nell'etichetta relazione tra entità (1:1, 1:N, 1:0..1)
    %% - Relazioni ordinate dalla root verso gli oggetti figli

    Direction LR

    %% ENTITÀ PRINCIPALI

    **EntityA** {
        STRING id PK "NOT NULL"
    }

    **EntityB** {
        STRING id PK "NOT NULL"
        OBJECT ChildEntity
    }


    ChildEntity {
        STRING field
    }

    %% RELAZIONI

    **EntityA** ||--|| **EntityB** : "1:1"
    **EntityB** ||--o{ ChildEntity : ""

    %% STILE

    style **EntityA** fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style **EntityB** fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style ChildEntity fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
