---
config:
  layout: elk
  theme: base
---

erDiagram

    %% diagram version: 0.0.1
    %% sources:
    %% - dc-pn-EcRichiesteMetadati.yaml
    %%   id: urn:send:postalizzazione:pn_ecrichiestemetadati
    %%   version: 0.0.1

    Direction LR

    pn_EcRichiesteMetadati {
        string requestId PK "NOT NULL"
        string clientRequestTimeStamp "NOT NULL"
        array eventsList "NOT NULL"
        object digitalRequestMetadata
        object paperRequestMetadata
        string requestHash "NOT NULL"
        string requestTimestamp "NOT NULL"
        string statusRequest "NOT NULL"
        long version "NOT NULL"
        string lastUpdateTimestamp "NOT NULL"
        string messageId
        string XPagopaExtchCxId "NOT NULL"
    }

    digitalRequestMetadata {
        string channel "NOT NULL"
        string correlationId "NOT NULL"
        string eventType "NOT NULL"
        string messageContentType "NOT NULL"
        string tags
    }

    paperRequestMetadata {
        string iun
        string printType
        string productType
        string requestPaId
        string vas
    }

    eventsList {
        object digProgrStatus
        string insertTimestamp "NOT NULL"
        object paperProgrStatus
    }

    pn_EcAnagrafica {
        string cxId PK "NOT NULL"
        string apiKey
        string mailReplyTo "NOT NULL"
        string pecReplyTo "NOT NULL"
        object senderPhysicalAddress "NOT NULL"
        string sqsArn "NOT NULL"
        string sqsName "NOT NULL"
    }

    senderPhysicalAddress {
        string address
        string cap
        string city
        string name
        string pr
    }

    pn_EcRichieste {
        string requestId PK "NOT NULL"
        string clientRequestTimeStamp "NOT NULL"
        object digitalRequestPersonal
        object paperRequestPersonal
        string requestTimestamp "NOT NULL"
        string XPagopaExtchCxId "NOT NULL"
    }

    pn_EcRichiesteConversione {
        string requestId PK
        string clientId
        string requestTimestamp
        array attachments
        object originalRequest
        long expiration
    }

    pn_EcConversionePDF {
        string fileKey PK
        string requestId
        long expiration
    }

    digitalRequestPersonal {
        array attachmentsUrls
        string messageText "NOT NULL"
        string qos "NOT NULL"
        string receiverDigitalAddress "NOT NULL"
        string senderDigitalAddress
        string subjectText "NOT NULL"
    }

    paperRequestPersonal {
        array arAddress
        string arCap "NOT NULL"
        string arCity "NOT NULL"
        string arName
        array attachments
        string receiverAddress
        string receiverAddressRow2
        string receiverCap
        string receiverCity
        string receiverCity2
        string receiverCountry
        string receiverFiscalCode
        string receiverName
        string receiverNameRow2
        string receiverPr
        string senderAddress
        string senderCity
        string senderDigitalAddress
        string senderName
        string senderPr
    }

    %% RELAZIONI
    
    pn_EcAnagrafica ||--|| senderPhysicalAddress : ""
    
    %% pn_EcRichiesteMetadati.XPagopaExtchCxId = pn_EcAnagrafica.cxId
    pn_EcAnagrafica ||--o{ pn_EcRichiesteMetadati : "1:N"

    %% pn_EcRichieste.XPagopaExtchCxId = pn_EcAnagrafica.cxId
    pn_EcAnagrafica ||--o{ pn_EcRichieste : "1:N"

    %% pn_EcRichieste.requestId = pn_EcRichiesteMetadati.requestId
    pn_EcRichieste ||--|| pn_EcRichiesteMetadati : "1:1"

    pn_EcRichieste ||--|| digitalRequestPersonal : ""
    pn_EcRichieste ||--|| paperRequestPersonal : ""

    %% pn_EcRichieste.requestId = pn_EcRichiesteConversione.requestId
    pn_EcRichieste o|--|| pn_EcRichiesteConversione : "0..1 : 1"

    %% pn_EcConversionePDF.requestId = pn_EcRichiesteConversione.requestId
    pn_EcRichiesteConversione ||--o{ pn_EcConversionePDF : "1:N"

    %% pn_EcRichiesteMetadati.digitalRequestMetadata
    pn_EcRichiesteMetadati ||--o| digitalRequestMetadata : "0..1"

    %% pn_EcRichiesteMetadati.paperRequestMetadata
    pn_EcRichiesteMetadati ||--o| paperRequestMetadata : "0..1"

    %% pn_EcRichiesteMetadati.eventsList[*]
    pn_EcRichiesteMetadati ||--o{ eventsList : "1:N"
    
    %% STILE

    style pn_EcAnagrafica fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style pn_EcRichieste fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style pn_EcRichiesteMetadati fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style digitalRequestMetadata fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style paperRequestMetadata fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style eventsList fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style pn_EcRichiesteConversione fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style pn_EcConversionePDF fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style senderPhysicalAddress fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style digitalRequestPersonal fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000
    style paperRequestPersonal fill:#FFFFFF,stroke:#000000,stroke-width:2px,color:#000000